#pragma config(Motor,  port4,           LLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RLift,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(vexRT[Btn5U] != 0)
			motor[LLift] = motor[RLift] = 127;
		else if(vexRT[Btn5D] != 0)
			motor[LLift] = motor[RLift] = -127;
		else
			motor[LLift] = motor[RLift] = 0;
	}
}
