#pragma config(Sensor, I2C_1,  mtrEnc,         sensorNone)
#pragma config(Motor,  port1,           runnertest,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Data to Log

1. Encoder Velocity
2. Voltage
3. Time Elapsed

*/

int time = 0;
int timeLast = 0;
int currEncode = 0;
int lastEncode = 0;
float encVel = 0;
float volts = 0;

task main()
{
	while(true)
	{
		motor[runnertest] = 127;
		timeLast = time;
		lastEncode = currEncode;
		time = nSysTime;
		currEncode = SensorValue[mtrEnc];
		encVel = (1.0 * (currEncode - lastEncode)) / (1.0 * (time - timeLast));
		volts = (nImmediateBatteryLevel / 1000.0);
		datalogDataGroupStart();
		datalogAddValue(3, volts);
		datalogAddValue(4, time);
		datalogAddValue(5, encVel);
		datalogDataGroupEnd();
		wait1Msec(20);
	}
}
