#pragma config(Sensor, dgtl1,  leftJumper,     sensorDigitalIn)
#pragma config(Motor,  port1,           BLDrive,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMG,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RMG,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FStrafe,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BStrafe,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BRDrive,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LDrive(int prw)
{
	motor[BLDrive] = motor[FLDrive] = prw;
}
void RDrive(int prw)//function to turn on the right drive
{
	motor[BRDrive] = motor[FRDrive] = prw;
}
void MGIntake(int pwr)
{
	motor[LMG] = motor[RMG] = pwr;
}
void Strafe(int pwr)
{
	motor[FStrafe] = motor[BStrafe] = -pwr;
}

//Auton funcs
void goRobit(int pwrL, int pwrR, int time)
{
	LDrive(pwrL);
	RDrive(pwrR);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
	wait1Msec(20);
}
//Driver Control funcs
void arcade(int move, int rot)
{
	LDrive(move + rot);
	RDrive(move - rot);
}
void tank(int pwrL, int pwrR)
{
	LDrive(pwrL);
	RDrive(pwrR);
}
/*
bool onLeft;
void LeftTest()
{
	if(leftJumper)
		onLeft = true;
	else
		onLeft = false;
}
void goRobit(int pwrL, int pwrR, int time, bool useLeftSwitcher)
{
	LDrive(pwrL);
	RDrive(pwrR);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
	wait1Msec(20);
}
void DefenseAuton(bool left)
{
	goRobit(127, 127, 1500);
	MGIntake(127, 350);
	goRobit(127, 127, 300);
}
*/
//Competition funcs/tasks
void pre_auton(){}
task autonomous()
{
	LeftTest();
}
task usercontrol()
{
	while(true)
	{
		arcade(vexRT[Ch3], vexRT[Ch4]);
		Strafe(vexRT[Ch1]);
		if(vexRT[Btn6U])
			MGIntake(127);
		else if(vexRT[Btn6D])
			MGIntake(-127);
		else
			MGIntake(0);
	}
}
