#pragma config(Motor,  port1,           FLDrive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FStrafe,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BStrafe,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LMG,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RMG,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LDrive(int prw)
{
	motor[BLDrive] = motor[FLDrive] = prw;
}
void RDrive(int prw)//function to turn on the right drive
{
	motor[BRDrive] = motor[FRDrive] = prw;
}
void MGIntake(int pwr)
{
	motor[LMG] = motor[RMG] = pwr;
}
void Strafe(int pwr)
{
	motor[FStrafe] = motor[BStrafe] = pwr;
}
//Auton funcs
void goRobit(int pwrL, int pwrR, int time)
{
	LDrive(pwrL);
	RDrive(pwrR);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
	wait1Msec(20);
}
//Driver Control funcs
void arcade(int move, int rot)
{
	LDrive(move + rot);
	RDrive(move - rot);
}
void tank(int pwrL, int pwrR)
{
	LDrive(pwrL);
	RDrive(pwrR);
}
//Competition funcs/tasks
void pre_auton(){}
task autonomous()
{

}
task usercontrol()
{
	while(true)
	{
		arcade(vexRT[Ch3], vexRT[Ch1]);
		Strafe(vexRT[Ch2]);
		if(vexRT[Btn5U])
			MGIntake(127);
		else if(vexRT[Btn5D])
			MGIntake(-127);
		else
			MGIntake(0);
	}
}
