#pragma config(Motor,  port1,           BLWheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           reserv1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           reserv2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           reserv3,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           reserv4,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           reserv5,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           reserv6,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FLWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FRWheel,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "Vex_Competition_Includes.c"




void LDrive(int prw){
	motor[BLWheel] = motor[FLWheel] = prw;
}
void RDrive(int prw){
	motor[BRWheel] = motor[FRWheel] = prw;
}
void lLift(int pwr){
	motor[LFLift] = motor[LBLift] = pwr;
}
void rLift(int pwr){
	motor[RFWheel] = motor[RBWheel] = pwr;
}
void claw(int pwr){
	motor[lClaw] = motor[rClaw] = pwr;
}

void goRobit(int pwrR, int pwrL, int time){
	RDrive = pwrR;
	LDrive = pwrL;
	wait1Msec(time);
	RDrive = 0;
	LDrive = 0;
}

void goLift(int pwr, int time){
	rLift = lLift = pwr;
	wait1Msec(time);
	rLift = lLift = 0;
}

void goClaw(int pwr, int time){
	claw = pwr;
	wait1Msec(time);
	claw = 0;
}

void pre_auton(){

}

task autonomous(){

}

task usercontrol(){
	while(true){
		vexRT[Ch2] = LDrive;
		vexRT[Ch3] = RDrive;
	}
}
