#pragma config(Motor,  port1,           fldrive,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           bldrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           brdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frdrive,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void arcade(int move, int rot)
{
	motor[fldrive] = motor[bldrive] = (move-rot);
	motor[frdrive] = motor[brdrive] = (move+rot);
}

task main()
{
	while(true)
	{
		arcade(vexRT[Ch3], vexRT[Ch4]);
	}
}
